DROP TABLE IF EXISTS BANK;

CREATE TABLE BANK (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS CLIENT;

CREATE TABLE CLIENT (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS STATEMENT_CONFIG;

CREATE TABLE STATEMENT_CONFIG (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
CLIENT_ID BIGINT NOT NULL,
BANK_ID BIGINT NOT NULL,
TRANSACTION_FIELDS VARCHAR(200)
);

ALTER TABLE STATEMENT_CONFIG ADD
FOREIGN KEY ( CLIENT_ID )
REFERENCES CLIENT (ID);

ALTER TABLE STATEMENT_CONFIG ADD
FOREIGN KEY ( BANK_ID )
REFERENCES BANK (ID);

ALTER TABLE STATEMENT_CONFIG
ADD CONSTRAINT CLIENT_BANK_UNIQUE
UNIQUE ( CLIENT_ID, BANK_ID );

DROP TABLE IF EXISTS STATEMENT_CATEGORY;

CREATE TABLE STATEMENT_CATEGORY_CONFIG (
    ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
    STATEMENT_CONFIG_ID BIGINT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    TAGS VARCHAR(200) NOT NULL
);

ALTER TABLE STATEMENT_CATEGORY_CONFIG ADD
FOREIGN KEY ( STATEMENT_CONFIG_ID )
REFERENCES STATEMENT_CONFIG (ID);

ALTER TABLE STATEMENT_CATEGORY_CONFIG
ADD CONSTRAINT CATEGORY_NAME_UNIQUE
UNIQUE ( STATEMENT_CONFIG_ID, NAME );

DROP TABLE IF EXISTS STATEMENT;

CREATE TABLE STATEMENT (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
PROCESSED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
FILENAME VARCHAR(50) NOT NULL,
CLIENT_ID VARCHAR(15) NOT NULL,
BANK_ID VARCHAR(15) NOT NULL
);

ALTER TABLE STATEMENT ADD
FOREIGN KEY ( CLIENT_ID )
REFERENCES CLIENT (ID);

ALTER TABLE STATEMENT ADD
FOREIGN KEY ( BANK_ID )
REFERENCES BANK (ID);

ALTER TABLE STATEMENT
ADD CONSTRAINT STATEMENT_UNIQUE
UNIQUE ( CLIENT_ID, BANK_ID, FILENAME );

DROP TABLE IF EXISTS STATEMENT_TRANSACTION;

CREATE TABLE STATEMENT_TRANSACTION (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  DOCUMENT_ID VARCHAR(50),
  TRANSACTION_DATE VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL,
  TRANSACTION_VALUE DOUBLE NOT NULL,
  CATEGORY VARCHAR(50) DEFAULT NULL,
  STATEMENT_ID BIGINT NOT NULL
);

ALTER TABLE STATEMENT_TRANSACTION ADD
FOREIGN KEY ( STATEMENT_ID )
REFERENCES STATEMENT (ID);

ALTER TABLE STATEMENT_TRANSACTION
ADD CONSTRAINT STATEMENT_TRANSACTION_UNIQUE
UNIQUE ( STATEMENT_ID, DOCUMENT_ID, TRANSACTION_VALUE );