DROP TABLE IF EXISTS OWNER;

CREATE TABLE OWNER (
ID VARCHAR(30) PRIMARY KEY,
NAME VARCHAR(100) NOT NULL
);

INSERT INTO OWNER (ID, NAME) VALUES
  ('alda', 'Aldaci Castro');

DROP TABLE IF EXISTS STATEMENT;

CREATE TABLE STATEMENT (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
START_DATE VARCHAR(10) NOT NULL,
END_DATE VARCHAR(10) NOT NULL,
FILENAME VARCHAR(50) NOT NULL,
OWNER_ID VARCHAR(30) NOT NULL
);

ALTER TABLE STATEMENT ADD
FOREIGN KEY ( OWNER_ID )
REFERENCES OWNER (ID);

ALTER TABLE STATEMENT
ADD CONSTRAINT STATEMENT_UNIQUE
UNIQUE ( OWNER_ID, START_DATE, END_DATE );

DROP TABLE IF EXISTS STATEMENT_TRANSACTION;

CREATE TABLE STATEMENT_TRANSACTION (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  DOCUMENT_ID VARCHAR(50),
  TRANSACTION_DATE VARCHAR(10) NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL,
  TRANSACTION_VALUE DOUBLE NOT NULL,
  CATEGORY VARCHAR(50) DEFAULT NULL,
  STATEMENT_ID BIGINT NOT NULL
);

ALTER TABLE STATEMENT_TRANSACTION ADD
FOREIGN KEY ( STATEMENT_ID )
REFERENCES STATEMENT (ID);

ALTER TABLE STATEMENT_TRANSACTION
ADD CONSTRAINT STATEMENT_TRANSACTION_UNIQUE
UNIQUE ( STATEMENT_ID, DOCUMENT_ID, TRANSACTION_VALUE );